# Workflow name
name: Frontend Continuous Deployment

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  # Automatic trigger on merge to the main branch
  pull_request:
    branches:
      - main
    # Execute the action on closed (merged) PR.
    types: [closed]
    paths:
      - 'starter/frontend/**'

env:
  NODE_VERSION: '18.x'
  BACKEND_URL: ${{ secrets.REACT_APP_MOVIE_API_URL }}
  ECR_REPOSITORY: frontend
  KUBECTL_VERSION: "v1.25.4"

jobs:
  frontend_cd:
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      
      - name: Install dependencies
        run: cd starter/frontend && npm ci
        
      - name: Linting
        id: lint
        run: |
          cd starter/frontend
          npm run lint
        continue-on-error: false

      - name: Tests
        id: tests
        run: |
          cd starter/frontend
          npm run test
        continue-on-error: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Logging into ECR to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the application using docker
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ GITHUB_SHA::7 }}
        run: |
              cd starter/frontend
              docker build --build-arg=REACT_APP_MOVIE_API_URL=${{ env.BACKEND_URL }} --tag=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Install kubectl
        id: kubectl-installer
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}
        
      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Configure kubeconfig file
        env:
          EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}
        run: |
              aws eks --region us-east-1 update-kubeconfig --name $EKS_CLUSTER

      - name: Configure image
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ GITHUB_SHA::7 }}
        run: |
            cd starter/frontend/k8s
            kustomize edit set image frontend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ GITHUB_SHA::7 }}
        run: |
          cd starter/frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy application to EKS Cluster

        run: |
            cd starter/frontend/k8s
            kustomize build | kubectl apply -f -